# Generated by Django 3.0 on 2019-12-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='harga_barang_col1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='harga_barang_col2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='harga_barang_col3',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='gambar_col1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='gambar_col2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='gambar_col3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='home',
            name='nama_barang_col1',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='nama_barang_col2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='nama_barang_col3',
            field=models.CharField(default='', max_length=30),
        ),
    ]
